#!/usr/bin/env bash
set -e

# Construct a string that can be passed to terraform to allow
# our aws credentials to be used
tf_credential_string="-var 'access_key=${HOBBY_AWS_ACCESS_KEY_ID}' -var 'secret_key=${HOBBY_AWS_SECRET_ACCESS_KEY}'"
tf_environment="-var 'environment=$2'"

# Validate number of args
[ "$#" != "2" ] &&
  echo "Error:  Requires 2 arguments" &&
  echo "Usage:  $ deploy [plan|apply|destroy] [dev|stg|prd]" &&
  exit

# Validate target environment (dev, stg, or prd)
( [ "$2" != "dev" ] && [ "$2" != "stg" ] && [ "$2" != "prd" ] ) &&
  echo "Error: unknown environment specified '$2', please use dev, stg, or prd" &&
  exit

cmd="terraform $1 ${tf_credential_string} ${tf_environment}"

#echo "${cmd}"
eval "${cmd}"
